#configmap
# Usage: You can use ConfigMaps to configure environment variables, command-line arguments, or configuration files within your pods.
# Injection: ConfigMap data can be injected into your pods as environment variables, command-line arguments, or mounted as files within the container's filesystem.

apiVersion: v1
kind: ConfigMap
metadata:
  name: nextjs-k8-app-config
data:
  NEXT_TELEMETRY_DISABLED: "1"