apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-load-target
  labels:
    app: db-load
    scenario: data-intensive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-load
  template:
    metadata:
      labels:
        app: db-load
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: db-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"    # Standard initial state
            cpu: "250m"        # Will be insufficient for reports
          limits:
            memory: "512Mi"    # Will cause pressure during peaks
            cpu: "500m"        # Will max out during processing
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"    # Standard memory allocation
            cpu: "250m"        # Standard CPU allocation
          limits:
            memory: "512Mi"    # Standard memory limit
            cpu: "500m"        # Standard CPU limit